{
 "title": "Vault and Postgres and Client",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "10s,30s,1m,5m,15m" },
   { "name": "quantile", "query": "0.5,0.9,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Consul: Vault service health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (consul_catalog_service_node_healthy{service_name=\"vault\"})",
     "legendFormat": "{{node}} healthy"
    },
    {
     "expr": "consul_health_service_status{service_name=\"vault\", status!=\"passing\"} > 0",
     "legendFormat": "{{node}} {{status}}"
    }
   ]
  },
  {
   "title": "client: healthy vault services found in Consul",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "client_vaults" }
   ]
  },
  {
   "title": "client: rpcs $interval rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(client_rpcs_total{job=\"client\"}[$interval])"
    }
   ]
  },
  {
   "title": "client: rpc_errors $interval rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(client_rpc_errors_total{job=\"client\"}[$interval])"
    }
   ]
  },
  {
   "title": "Vault Update KV $interval Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_route_update_kv__count[$interval])"
    }
   ]
  }
 ]
}