global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: consul
    metrics_path: /v1/agent/metrics
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["localhost:8500"]

  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    bearer_token_file: /etc/prometheus/vault-scrape-token
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd_configs/vault*.json




